version: "3.9"

services:
  server:
    build: .
    ports:
      - "5000:5000"
  db:
    image: "postgres"
    ports:
      - "4321:5432"
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "donnchad"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
