version: "3.9"

services:
    db:
        image: "postgres"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "password"
            POSTGRES_DATABASE: "postgres"
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"

    # server:
    #   build: .
    #   ports:
    #     - "5000:5000"
    #   environment:
    #     POSTGRES_PASSWORD: "password"
    #     POSTGRES_USER: "donnchad"
    #     JWT_SECRET: "SanskarRandiHo"
