version: "3.9"

services:
  db:
    image: "postgres"
    ports:
      - "4321:5432"
    environment:
      POSTGRES_USER: "donnchad"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DATABASE: "donnchadDB"

  # server:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     POSTGRES_PASSWORD: "password"
  #     POSTGRES_USER: "donnchad"
  #     JWT_SECRET: "SanskarRandiHo"
  # db:
  #   image: "postgres"
  #   ports:
  #     - "4321:5431"
  #   environment:
  #     POSTGRES_PASSWORD: "password"
  #     POSTGRES_USER: "donnchad"
  # redis:
  #   image: "redis"
  #   ports:
  #     - "6379:6379"
